# Generated by Django 5.0.6 on 2024-07-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_doctorprofile_user_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
