# Generated by Django 5.0.6 on 2024-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_patientprofile_blood_glucose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='allergies',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_glucose_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_pressure_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
