# Generated by Django 5.0.6 on 2024-07-27 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
