# Generated by Django 5.0.6 on 2024-07-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='call_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
