# Generated by Django 5.0.6 on 2024-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_options_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='unique_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
